configdemo:
  user:
    name: 小红
    age: 15
    hobbies:
      - 唱歌_${random.value}
      - 跳舞_${random.uuid}
    dog:
      age: 2
      name: ${configdemo.user.name}_小黄
    clazz:
      name: 李四
      age: 12
    books: { book1: 中文${configdemo.user.name},book2: 英语 }